# Change these first
owner: youyou-sudo # Your GitHub organization or username, where this repository lives
repo: upptime-s # The name of this repository

sites:
  - name: 紫缘社
    url: https://galzy.moe
    type: globalping
  - name: 紫缘社 - Search
    url: https://galzy.moe/search?q=clannad
    type: globalping
  - name: 鲲 Galgame 论坛
    url: https://www.kungal.com
    type: globalping
  - name: 鲲 Galgame OAuth
    url: https://oauth.kungal.com
    type: globalping
  - name: 鲲 Galgame Wiki
    url: https://wiki.kungal.com
    type: globalping

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.galrc.eu.org
  # baseUrl: /your-repo-name
  logoUrl: https://files.catbox.moe/ejy8x6.webp
  name: Upptime
  introTitle: "**Upptime-s**是开源的正常运行时间监控和状态页面，完全由 GitHub 提供支持."
  introMessage: 这是忧忧的站点健康度检测喵～❤️
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
